### ISSUE TITLE
Link to https://f000.backblazeb2.com/ is broken

### ISSUE THREAD

**Issue by chrhad** [mesolitica/malaysian-dataset#346]
As the datasets are stored there, they can't be downloaded. Have the datasets been moved elsewhere?

**Comment by huseinzol05** [comment]
which dataset?

**Comment by chrhad** [comment]
The summarization dataset, for example: https://f000.backblazeb2.com/file/malay-dataset/summarization/dailymail/translated-dailymail-test.json

**Comment by huseinzol05** [comment]
moved to https://huggingface.co/datasets/mesolitica/translated-cnn-dailymail/tree/main
