### ISSUE TITLE
Request Dataset Buku Resepi Makanan Melayu Malaysia 

### ISSUE THREAD

**Issue by lorarianz** [mesolitica/malaysian-dataset#384]
Request Dataset Buku Resepi Makanan Melayu Malaysia 

- Resepi Masakan Melayu
-  Resepi Masakan Malaysia

**Comment by aisyahrzk** [comment]
Hi there,

you could try looking into our crawled dataset from myresepi.com and resepichenom website. 

- https://github.com/mesolitica/malaysian-dataset/tree/master/crawl/myresipi.com
- https://github.com/mesolitica/malaysian-dataset/tree/master/crawl/resepichenom.com
