### ISSUE TITLE
Why all the link dataset not found? 

### ISSUE THREAD

**Issue by Michelle245** [mesolitica/malaysian-dataset#407]
All displayed 404 not found when click the link 

example: 
https://f000.backblazeb2.com/file/malay-dataset/dumping/twitter/manglish.json
https://f000.backblazeb2.com/file/malay-dataset/dumping/singlish/singlish.txt

![Screenshot 2024-08-02 154534](https://github.com/user-attachments/assets/38d9eee1-a09e-4d28-b086-2872e3e0cb67)

**Comment by huseinzol05** [comment]
We changed to huggingface repository, we will update the urls ASAP, sorry sir

**Comment by huseinzol05** [comment]
Feel free to check corpus at https://huggingface.co/datasets/malaysia-ai/pretrain-text-dataset
