### ISSUE TITLE
Link for Kamus Dewan

### ISSUE THREAD

**Issue by whirosss** [mesolitica/malaysian-dataset#410]
Hi , im unable to access https://huggingface.co/datasets/mesolitica/kamus-dewan/raw/main/Kamus_Dewan_Bahasa_Edisi_Keempat.json  due to invalid username or password . Can you help fix that? ;) 

![Screenshot_20241009-141414](https://github.com/user-attachments/assets/4d9e5c88-4a55-4624-8a59-61b22a68acb5)

**Comment by huseinzol05** [comment]
We moved to https://huggingface.co/datasets/malaysia-ai/crawl-my-website/tree/main, sorry forgot to update the readme
